### ISSUE TITLE
Investigate unexpected resource disappearance

### ISSUE THREAD

**Issue by brandond** [rancher/kine#61] opened 2020-11-10 01:25 UTC
We have observed an instance of a single Kubernetes resource unexpectedly disappearing from the apiserver. Due to lack of apiserver audit logs it is unclear if it was removed at the Kubernetes level by a client operation, or if it was somehow incorrectly deleted by compaction code. K3s logs do not show any errors during the period in which we suspect the object was removed.

The backend datastore was a two-node AWS RDS Aurora MySQL cluster running version `5.7.mysql_aurora.2.09.0`. K3s version was `k3s v1.18.10+k3s2`.

We need to do additional testing of multi-node database clusters to ensure that all operations are safe when multiple kine instances are connected to a database cluster. In initial review of the code does not turn up any remaining obviously unsafe operations. There were some questions about transaction safety of inserts, but an initial cursory review of the go-mysql code suggests that this should be safe to use the way we're using it.

gz#13317

**Comment by MerlinDMC** [comment] 2020-11-10 09:41
Interesting to see this popping up here as I'm in the process of trying to find the cause for our resource disappearance.
We however run Kubernetes 1.18 against a normal Etcd cluster and observed secrets, deployments and statefulsets getting terminated in the events stream during higher load on the API server and Etcd. (we replaced worker nodes and the scheduler started reassigning workloads)

That leaves me slightly worried now as that probably rules out our slightly older Etcd version and it might be in the API server 😞 

And while I'm here - thx for https://github.com/etcd-io/etcd/pull/11776 as that is currently blocking my test environment 😉

**Comment by brandond** [comment] 2020-11-10 09:46
@MerlinDMC if you've seen something similar on clusters running stock etcd that makes me feel slightly more optimistic that there isn't some weird issue with kine that's disappearing our resources out from underneath us.

**Comment by MerlinDMC** [comment] 2020-11-10 09:46
yes - but I was just about to try kine as a replacement to get rid of the problem 🤣

**Comment by brandond** [comment] 2020-11-10 10:57
Can you share any more details on what you were seeing? Was the apiserver actually deleting things from etcd? How were you monitoring the issue?

**Comment by MerlinDMC** [comment] 2020-11-10 15:13
I was monitoring status of the deployments via `kubectl get --all-namespaces events -w`. At some point during the rollout of our services to new nodes (roughly 1000 pods) I did see terminations for a lot of deployments in the event stream.

I'm not sure yet if the apiserver did issue those deletes or if it did read keys from Etcd and didn't get all the data back. No person however did issue deletes.

I'm trying to get a test scenario up that has the same application load so we can try to forcefully get into the same issue again and collect more data.

**Comment by brandond** [comment] 2020-11-13 04:27
We have identified an issue that could, under certain circumstances, cause data loss within the kine back-end database, including removal of random resources from the Kubernetes datastore.

Like etcd, kine stores all changes to the MVCC store as rows in a database. We use SQL instead of BoltDB like etc, but both need to be compacted periodically to remove old revisions from the history lest the store grow out of control. Kine does this internally by tracking relationships between resource versions in the `prevous_rev` column of the database - each version of a resource points to the previous version via this column. There is also a special key with the name `compact_rev_key` that notes the revision that we have compacted up to, so that we can authoritatively respond with the appropriate error when a client asks for an old version of a resource, and that resource is not found.

In an unfortunate early design choice, we store the compact revision in the `prev_revision` column of this entry, rather than the `value`. This means that we need to exclude it when selecting old resource versions to delete. 

Recent changes to improve compaction efficiency by moving the compact logic from go code to pure SQL incorrectly handled the `compact_rev_key` entry - we excluded it from deletion instead of excluding it when building the list of revisions that are safe to delete.

**Closed** 2020-11-13 07:23 UTC

**Comment by rancher-max** [comment] 2020-11-13 17:01
#### Validated on all three releases: `v1.17.14-rc1+k3s2`, `v1.18.12-rc2+k3s1`, and `v1.19.3-rc1+k3s3`

- Performed the test steps listed in https://github.com/rancher/kine/pull/62
- Validated standard regression checks on the cluster are passing (create, scale, delete, modify workloads, secrets, etc.)
- ensured compaction is still working proeperly
